### ISSUE TITLE
5.0+ (minSDK\API=21), can you pls downgrade?

### ISSUE THREAD

**Issue by drogga** [ThePBone/RootActivityLauncher#1]
Hi, I couldn't find another (better) way to contact you, so here I am, writing a issue...
Anyway, I saw that the MinSDKversion \ API is 21 = 5.0+, but can you please make it compatible with older android versions too, like downgrade\lower it down, let's say to 4.0+ (14) and build a .apk file of it ?
Thanks in advance ;)

**Comment by timschneeb** [comment]
Sure, commit 076fe74f2f3cae05862480e176a87b5b7e6e0a62 adds compatibility down to Android 4.0.

A compiled APK is available on the [release page](https://github.com/ThePBone/RootActivityLauncher/releases).

**Comment by drogga** [comment]
Thanks, that was a damn fast, just installed it and it looks like it's based on a old build that doesn't support searching, so can you please use 1.9.1 \ 1.9.2 as a base, there's also a problem with some huge icons for some app's activities, especially when you go to "edit shortcut", which is fixed by a user in\on 4PDA, and I used it to make it with a Dark UI theme (your mod\fork also is not in Dark on Android 4, and there's no way to switch\activate it), so if you need more info just ask, tho it will be easier for me to just E-Mail you instead - in case you share a address of course (BTW, I don't have any social media platforms accounts - including Telegram or other of this kind).

Can the debug info (I think it has one) be removed to make it lighter in file size - couple of KBs, like the original maybe...?

**Comment by drogga** [comment]
@ThePBone do you think that a similar *root mod* can be done over HashDroid {com.hobbyone.HashDroid} - to be able to read and calculate Hash Sumes of files that are located anywhere on the storage (let's say from /data/app for example...), without the need you to first copy it to the internal storage (/mnt/*) ?

**Comment by timschneeb** [comment]
> can you please use 1.9.1 \ 1.9.2 as a base

Maybe I'll do that sometime in the future but I don't have enough time to reimplement it again at the moment. The original purpose was to restore the functionality of [DerekZiemba's RootActivityLauncher](https://github.com/DerekZiemba/RootActivityLauncher) on Android 8 or later.

> not in Dark on Android 4

The new material UI does not support dark mode on Android 4.4 and lower, because the night mode switch in the system settings is missing on these OS versions (could be worked around by adding an explicit switch into the app, but that's rather an aesthetic fix).

> Can the debug info (I think it has one) be removed to make it lighter in file size - a couple of KBs, like the original maybe...?

No, Java/JVM binaries generally won't get any lighter with stripped debug information (it does make a difference on low-level apps written in C/C++ though). This fork is a bit bigger because it includes the latest material UI and is written in Kotlin (which also requires an extra library)

> do you think that a similar root mod can be done over HashDroid?

Since it's open-source yes, but it makes use of the built-in Android SAF folder/file selector which would need to be replaced with a custom implementation.

Anyway, there are already apps that calculate checksums using Root, for example, most root file browsers like <https://play.google.com/store/apps/details?id=com.jrummy.root.browserfree>.

**Comment by drogga** [comment]
Ok, please do so, as soon as you can. ;) I blame myself for not noticing earlier that your git repo fork mod is based on\uses\contains old version, without the search implemented or any of the fixes for newer androids..., even before asking you to make it compatible with android 4.X !

The solution to have a dark ui theme everywhere (4\5+) is to just edit the "AppBaseTheme" from the resources "values" to "DeviceDefault", and\but "Material" for "values-v21"'s styles.xml and not touch anything else regarding the theme (at least that's how it is for the original).

Regarding Hash Droid - new versions use SAF (I hate them), but v.3.3 uses a build-in file picker\chooser\browser\explorer, but it does lead to a bad storage path for newer android versions and it can't get access to anything, luckily I managed to mod it and change the file select path to "/mnt" and now works and can read files without a problem, tho I didn't tested it on newer than 7 Nougat, but it will probably work on 10, maybe not on 11 because of the stupid new storage rules, permissions and so on..., I even reEnabled the gradient background, which looks awesome according to me, better than a plain black\dark or white, but I can't do anything else to it, because I don't have the necessary skills, like you do.

File Managers\Explorers\Browsers does not support\can't calculate that much hash types like this dedicated tool, not only I have my preferred file managers that I use (Root Explorer and MT Manager), but also all of those kind of apps show\calculate only SHA1, MD5 and CRC32, but not the other 11 type of check\hash sumes that Hash Droid supports and sometimes I need.
